ruby/setup-ruby

- README.md
- dist/index.js
- ruby-builder-versions.js
Not exactly sure what the process for adding new rubies is, I just "copied" 7f508b5101e9cc2d7cbb7851689507771d9ff6c6.
> Add JRuby 9.2.11.0

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- index.js
> Use the Bundler version from Gemfile.lock, otherwise install latest

- dist/index.js
- index.js
> Treat error from restoring the cache as a cache miss

- README.md
- action.yml
- dist/index.js
- index.js
> Support multiple gemfiles

- .github/workflows/test.yml
- action.yml
- dist/index.js
- index.js
> Allow an exact Bundler version, and use the exact same version if present in lockfile

- bundler.js
- dist/index.js
Fix #148 
@eregon could you run your tests with this branch?
> Enforce bundler version 1 for ruby 2.3.0 and 2.3.1

- README.md
https://github.com/actions/virtual-environments/blob/dee50eebffa60a7dd9149033675d44a027dd6b33/README.md#available-environments
> ubuntu-latest is ubuntu-20.04 now

- README.md
- action.yml
- bundler.js
- common.js
- dist/index.js
- index.js
* Fixes https://github.com/ruby/setup-ruby/issues/358
> Use the Bundler shipped with that Ruby by default

- bundler.js
- common.js
- dist/index.js
See https://github.com/ruby/setup-ruby/issues/358#issuecomment-1195899304
> Use latest Bundler on CRuby 2.6 and 2.7 as their default Bundler is too old

- bundler.js
- common.js
- dist/index.js
> Fix automatic bundler installation on JRuby 9.2

- README.md
- bundler.js
- common.js
- dist/index.js
- index.js
- package.json
- ruby-builder.js
- windows.js
- yarn.lock
* And give instructions for that case.
* Get the OS and OS version ourselves since some users set ImageOS incorrectly.
* This partially reverts commit ad1ebae995ccc3584a094574eafc5826942ec8d4.
> Detect self-hosted runners not matching a GitHub-hosted runner image

- dist/index.js
- ruby-builder.js
* Fixes https://github.com/ruby/setup-ruby/issues/191
> No longer remove the prefix before extraction, extracting should be idempotent

- README.md
Use current ruby version in examples.
> Update ruby version in `README.md`

- action.yml
> Update deprecated Node 16 to 20

- README.md
> Update sample ruby version in `README.md`

- dist/index.js
- ruby-builder.js
* See https://github.com/oracle/truffleruby/issues/3390
> Workaround bug in XCode 14.2 linker not respecting RTLD_LAZY

- README.md
it matches with action.yml
https://github.com/ruby/setup-ruby/blob/50ba3386b050ad5b97a41fcb81240cbee1d1821f/action.yml#L9
> docs: update ruby-version comment

- dist/index.js
- index.js
* Reverts ruby/setup-ruby#785
* https://github.com/ruby/setup-ruby/issues/787
* https://github.com/ruby/setup-ruby/issues/788
> Revert "Add printing of the lockfile after installation"

- .github/workflows/test.yml
- common.js
- dist/index.js
Depends on
- https://github.com/ruby/ruby-builder/pull/25
- https://github.com/ruby/jruby-dev-builder/pull/18
> Add JRuby for Windows on Arm

- .github/workflows/test.yml
- action.yml
- package.json
Reverts ruby/setup-ruby#804
See https://github.com/ruby/setup-ruby/pull/804#issuecomment-3315203960
See https://github.com/ruby/setup-ruby/issues/806#issuecomment-3315201699
> Revert "feat: upgrade to node 24"
