- dist/index.js
- windows.js
Add `bin` to Windows MSYS2 paths.  I just edited the files for now...
> Correct Windows MSYS2 paths

- dist/index.js
- index.js
This sets CLASSPATH to an empty string before the download/installation.
Not sure whether this is considered a valid thing to do, but the 'Ruby Info' step in https://github.com/MSP-Greg/use-ruby-action-info/runs/381796430 completes with it.
Using yarn now.
> Set CLASSPATH to empty for JRuby

- .github/workflows/test.yml
- dist/index.js
- generate-ruby-installer-versions.rb
- index.js
- package.json
- ruby-install-builder.js
- ruby-installer-versions.js
- windows.js
> Use the latest builds for a given Ruby release in Windows

- dist/index.js
- windows.js
From a bit of quick research, the systems used for Actions have both a HD and an SSD.  Added code to place the Windows Ruby on the SSD, assuming it is `d:`
> Use SSD drive for Windows Ruby location

- .github/workflows/test.yml
- dist/index.js
- windows.js
* See https://github.com/ruby/setup-ruby/issues/19
> Fix PATH on Windows

- README.md
Hi 👋 
The `${{ matrix.os }}` is empty when only testing on one platform. We can suggest to use `${{ runner.os }}` instead.
> Use runner.os for testing against one platform

- .github/workflows/test.yml
- dist/index.js
- generate-windows-versions.rb
- index.js
- windows-versions.js
- windows.js
1. Add ruby-loco mingw and mswin
2. Adjust workflow for mswin - 'ridk version' & 'c extension' steps
3. Allow head, mingw, & mswin to be used without ruby prefix
4. win_names.yml_ tests the above, fails on some non Windows jobs deliberately
> Add ruby-loco mingw and mswin

- dist/index.js
- ruby-builder.js
On Windows, the `extractTar` function in @actions/exec just shells out to the git tar command.
Use the native tar, `C:\Windows\system32\tar.exe`.
> ruby-builder.js - Win32 - use C:\Windows\system32\tar.exe

- dist/index.js
- ruby-builder.js
Given that we know the compression type of the files being extracted, I should've changed it earlier...
> Simplify 'tar' in ruby_builder.js - downloadAndExtract

- .github/workflows/test.yml
- dist/index.js
- index.js
- package.json
- ruby-builder.js
- windows.js
- yarn.lock
REVISED - 3 commits
1. Update package.json & yarn.lock
---
2. test.yml - Add which/where, mswin vcvars*.bat ENV
* Add which/where for ruby and rake
* Remove call %VCVARS% code for mswin
* Loosen some step 'if' checks
---
3. Reorganize path manipulation, mswin tools ENV
* Use only one 'core' call to set PATH
* clean PATH
* Windows mswin - add vcvars*.bat changes to ENV
> reorganize Path handling, add MSVC env to action

- CONTRIBUTING.md
For someone unfamiliar with `yarn`, the original output does not make it clear that it should be run as a bare command line to install dependencies. Since the default behavior is `yarn install` make that explicit in the doc.
> Make it clear this is a command to be run

- ruby-builder-versions.js
The jruby-launcher needs to be tested at least one major JRuby version back. In addition, there are users out there running JRuby 9.1.x that may be unable to upgrade at present.
> Add JRuby 9.1.17.0 for testing

- dist/index.js
- windows.js
1. Use 'Git for Windows' cert.pem file
2. Add MSYS2 to path for mswin (after msvc additions)
3. Rearrange code for cleanup when MSYS2 is added to Window image
The comment below precedes code that can be removed when MSYS2 is added.
```
// Remove when Actions Windows image contains MSYS2 install
```
> Update for Actions Windows MSYS2 install

- .github/workflows/test.yml
- README.md
- dist/index.js
- windows.js
Three commits:
1. 'windows.js - install old MSYS devkit for MinGW 2.2 and 2.3' - adds code to install MSYS DevKit for Windows MinGW  2.2 and 2.3 Rubies
2. 'Actions - add gcc --version output for MinGW Rubies' - added code to show version of gcc in Path.  2.2 and 2.3 should show 4.7.2 gcc, 2.4 and later should show 8.3.0 or later
3. 'README.md - add info re MSYS install for MinGW 2.2 and 2.3 Rubies'
> Windows 2.2 & 2.3 - install old MSYS DevKit

- dist/index.js
- windows.js
In my fork, the 2.2 & 2.3 tests took 14 and 16 sec.  The previous CI here took 27 ands 26 sec.
Surprised that the difference was that large.  Sorry for moving it.
> Windows MSYS - move install to ssd drive

- dist/index.js
- windows.js
To avoid things like:
```yml
env:
MAKE: "make" # to not try to use gmake on Windows
```
I had similar code in pkgs.  Should be here.  I also checked, and this is the last of things affecting 'build tools' (that have been noticed)...
> Windows - set ENV['MAKE'] to avoid conflicts with other Actions tools

- action.yml
- dist/index.js
- index.js
This commit adds a `working-directory` option. This is useful for cases where files like `.ruby-version` and `Gemfile.lock` aren't located in the root directory. In my case, this is because I'm working in a monorepo, where my Ruby project is located in its own subfolder.
> Add support for setting a working directory

- README.md
`bundle install --deployment` should be used on CI environments - it sets additional options beyond the install path (ensures the Gemfile.lock is checked in, up to date, etc). https://bundler.io/v2.0/man/bundle-install.1.html#DEPLOYMENT-MODE
`bundle --retry 3` is the default and does not need to be specified. https://bundler.io/v2.0/man/bundle-config.1.html#LIST-OF-AVAILABLE-KEYS
> Use the `--deployment` flag for bundle install

- .github/workflows/test.yml
- README.md
- action.yml
- common.js
- dist/index.js
- index.js
- package.json
- yarn.lock
> Automated bundle install and caching

- dist/index.js
- index.js
External actions may use setup-ruby, and some actions make changes/additions to the build environment.  These may be needed for dependencies.
Hence, allow those external actions to run code before 'bundle install'.  This is done by passing a function as a parameter to run().
> Allow running external function before 'bundle install'

- README.md
This makes notes about how you can get this action to work with self-hosted runners if you meet certain conditions. This configuration has been implemented and tested in a production environment.
> Update README to reflect conditions for self-hosted runners

- dist/index.js
- index.js
Fixes part of #52 - doesn't work with `gems.rb`.
> Add support for `gems.rb`/`gems.locked` during `bundle install`.

- .github/workflows/test.yml
- common.js
- dist/index.js
- index.js
- ruby-builder.js
- windows.js
Three Commits:
A. ENV setup, Windows tar, Windows bash shell
B. Add envPreInstall, common.setupPath, use MSYS2 bash for Windows bash
1. index.js - envPreInstall - sets ENV values for runners
2. common.js - setupPath - collects all Path operations into one function, runs before Ruby install
3. Add MSYS2 paths to all Windows builds for MSYS2 Bash use
C. Add Actions 'bash test' and 'Windows JRuby' (gem install sassc) steps
Closes #81
> ENV setup, Windows tar, Windows bash shell

- dist/index.js
- index.js
Basically use specific bundler version until lockfile is created. Fixes #117, test run which previously failed can be found [here](https://github.com/ojab/watir-rails/runs/1500872128).
> Fixup bundler version for rubies with bundler as a default gem

- dist/index.js
- index.js
Looks like we can't delete environment variable and we cannot set envvar for the single step from JS, so let's just set requested bundler version to envvar if it's set, so
```yaml
- use: ruby/setup-ruby@v1
with:
ruby-version: 2.7
env:
BUNDLER_VERSION: 1
```
will do the trick.
> Pass BUNDLER_VERSION only to commands that need it and not for the whole workflow

- dist/index.js
- index.js
> install specific bundler version when minor and patch versions are defined

- bundler.js
- dist/index.js
The fix for rubygems/rubygems#3570 was released with bundler 2.2.0.rc.1.
> Remove bundler enforcement on ruby 2.3

- README.md
As described in the comment, due to a bug discussed on https://github.com/actions/runner/issues/849,
we currently have to use quotes for  '3.0' as a workaround.
This change makes it easy for people not to remove quotes as they misunderstand it's a typo.
> Add a comment about version quotations to README

- common.js
- dist/index.js
JRuby 9.3 will ship with bundler and jruby-head already does.  This PR, like truffleruby, will not bother installing bundler since it is already installed.
I was confused about one thing.  When JRuby 9.3 is released how do we change this action to say bundler is already installed?  ruby-version appears to only report 'jruby' and 'jruby-head' to this JS function.  I would like to make sure when we do put out that version we are not again reinstalling bundler.
> JRuby 9.3 (head) and forward ships bundler

- README.md
- action.yml
- bundler.js
- dist/index.js
- index.js
attempt to fix #174
implements the solution proposed in https://github.com/ruby/setup-ruby/issues/174#issuecomment-839625379
> cache version option

- .github/workflows/test.yml
9.2.18.0 has been released, so this should work now.
Follow-up to #188
> Enable SassC test on JRuby on Windows

- .github/workflows/test.yml
- common.js
- dist/index.js
Commits:
**'Improve Path info in CI, add workflow_dispatch'** - only changes Actions, shows 'PATH' step info with each PATH segment on an individual line, display Windows Path in a normal window style.
**'Update runtime logging of Path adjustments, show additions'** - the runtime logging had a group named 'Cleaning Path'.  It only showed path deletions.  Changed name to 'Modifying Path', and added logging of path additions.
> Runtime - Add logging of both PATH removals & additions, CI - improve 'PATH' step

- README.md
This ensures the gemfile can be found when a step changes the working directory.
---
A little while back, I encountered an issue when setting up CI for Rails gems and using the `bin/test` script that Rails generates.  This addition fixed it.  I had written myself a reminder to submit this PR, but, unfortunately, I didn't write down any further details.  But I hope this helps someone.
> Suggest absolute path for BUNDLE_GEMFILE

- .github/workflows/test.yml
- README.md
- bundler.js
- common.js
- dist/index.js
- index.js
- ruby-builder-versions.js
- windows.js
* On Windows there are no 64-bit builds of Ruby 1.9.
* Use floatVersion() in more cases instead of regexps.
* Rely on ~/.gemrc to not install gem docs.
Fixes https://github.com/ruby/setup-ruby/issues/204
> Add Ruby 1.9 on Linux and macOS

- README.md
I ran into an issue when I was using this on a self hosted runner, I noticed an error:
> The environment variable ImageOS must be set (Self hosted runner)
This is a small update in the Readme to help other people find the problem
> Clarify the use of ImageOs on self hosted runners

- dist/index.js
- package.json
- yarn.lock
The new version of `@actions/cache` allows for caching dependencies upto 10GB. 
Closes Issue: https://github.com/ruby/setup-ruby/issues/231
> Updating actions/cache version 1.0.8

- .github/workflows/test.yml
- bundler.js
- dist/index.js
- windows-versions.js
Follow up to https://github.com/oneclick/rubyinstaller2/issues/255#issuecomment-1003266597.
This PR adds Ruby 3.1.0 to windows-version.js.
> Support Ruby 3.1.0 for Windows

- .github/workflows/test.yml
- common.js
- dist/index.js
- generate-windows-versions.rb
- index.js
- package.json
- ruby-builder.js
- windows-versions.js
- windows.js
- yarn.lock
See commits.  On Windows-2022 image, code adds the MSYS2 packages from 'base-devel' group needed for Ruby builds.
Also adds ENV variables by running `ridk enable`, testing for the file's existence first.  Uses code similar to the code for mswin's vcvars script.  Parses the output of the set command, so it's not dependent on ridk's output.
Windows 2019 Image - No changes when using with a mingw Ruby. When using a ucrt Ruby, a pre-built ucrt 7z file is installed from https://github.com/MSP-Greg/setup-msys2-gcc/releases/tag/msys2-gcc-pkgs.  The 7z files are generated three times a day in that repo.
Windows 2022 Image - Since the image has no MSYS2 build tools installed, both an MSYS2 package and a gcc package (mingw or ucrt) are installed from the MSP-Greg/setup-msys2-gcc repo.
> Windows - Add support for ucrt & Windows-2022 image

- .github/workflows/test.yml
- README.md
- action.yml
- dist/index.js
- index.js
- package.json
- rubygems.js
Implements #228.
I guess TruffleRuby needs some special handling. Also, I'd like to ask what's the recommended way to try out my changes when working on a PR?
> Add a new input to optionally update RubyGems

- README.md
> add `libgmp` to requirements for self-hosted runners

- README.md
The culprit ended up being https://github.com/jruby/jruby/issues/6745, which was released with JRuby 9.2.20.0.
Happy to change the wording to make this clear instead of removing the reference.
> Clarify reference to a known issue now fixed

- .github/workflows/test.yml
- common.js
- dist/index.js
- package.json
- windows.js
- yarn.lock
Updates for mswin builds, no 'bugs' involved.  Commit info:
1. '[package.json and yarn.lock](https://github.com/ruby/setup-ruby/commit/55996aeeb97e7655ea5afacd23e44b6600db10d3)' - 'housekeeping'
2. '[Windows mswin - update addVCVARSEnv](https://github.com/ruby/setup-ruby/commit/c3a022e6a96d4f8c0ae1cf414623a5f4c19e57ec)' - Currently the 'vcvars.bat' file's path was found via a switch/select/case statement that hard-coded the Actions windows image string.  A PowerShell module ([vssetup.powershell](https://github.com/microsoft/vssetup.powershell)) is available for finding information about Visual Studio installs, and it is installed on all Actions Windows runners.  Use the module so hard-coded image strings aren't needed.
3. '[Windows mswin - use ucrt64 tools instead of …
> Windows - updates for mswin builds

- .tool-versions
- action.yml
According to the release policy of Node.js,
Node.js v12 reached EOL (end-of-life).
https://nodejs.org/en/about/releases/
I think ruby/setup-ruby is ready to update Node.js to v16
because GitHub Actions runners support v16.
https://github.com/actions/runner/issues/772
> Update Node.js from v12 to v16

- .github/workflows/test.yml
- dist/index.js
- windows.js
Similar to current code, which install all packages/tools for building mingw and ucrt Rubies, this PR installs the set of packages from [microsoft/vcpkg](https://github.com/microsoft/vcpkg) needed to build an mswin Ruby.
This will also allow all Ruby extension gems/std-lib repos to build on mswin without using [ruby/setup-ruby-pkgs](https://github.com/ruby/setup-ruby-pkgs).
Closes #331
> Windows - install vcpkg archive from setup-msys2-gcc when using mswin builds

- .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- pre-commit
It says it is recommended to copy the pre-commit to our local pre-commit when committing to this repository.
https://github.com/ruby/setup-ruby/blob/master/CONTRIBUTING.md
> It is recommended to add this as a git pre-commit hook:
> ```
> $ cp pre-commit .git/hooks/pre-commit
> ```
When we do this on our macOS environment, we get `No such file or directory` as follows.
```bash 
❯ git commit
fatal: cannot run .git/hooks/pre-commit: No such file or directory
```
The above error is likely because `/usr/bin/sh` is not supposed to exist on macOS.
(Linux may possibly have `/usr/bin/sh`.)
Since it seems redundant for someone to edit pre-commit for every contribution in a macOS environment, we suggest using `/bin/sh` for shebang so that it can be used without editing pre-commit in the macOS …
> Change pre-commit shebang to `/bin/sh`

- README.md
According to GitHub Blog ubuntu-latest is now 22.04.
see: https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
> ubuntu-latest is now 22.04

- bundler.js
- dist/index.js
Resolved https://github.com/ruby/setup-ruby/issues/422
> Bundler-2.4 requires Ruby 2.6 or later

- bundler.js
- dist/index.js
This is so that I don't forget to do this before next year's Bundler release.
I also fixed a small bug introduced with #423 where an explicit and valid input configured by users like `bundler: 2.2` would be ignored and "bundler: 2.3" would be installed instead.
> Bundler higher than ~> 2.4.0 will require Ruby 3.0 or later

- .github/workflows/test.yml
Use the same Ruby as the previous test, since it's very related, but use a newer RubyGems to force the upgrade case.
> Reenable fixed RubyGems test

- dist/index.js
- windows.js
The RubyInstaller2 builds of 3.2 and 'head' are using a custom OpenSSL 3 package.
[ruby/setup-msys2-gcc](https://github.com/ruby/setup-msys2-gcc), which assembles archive files of Windows build tools, has been updated and now creates archives (named with suffixes) that allow for different OpenSSL versions.  See the [release list](https://github.com/ruby/setup-msys2-gcc/releases/tag/msys2-gcc-pkgs).
This PR adds code to use the correct archive file.
See ['Windows, OpenSSL, Ruby 3.2' discussion](https://github.com/ruby/setup-ruby/discussions/428).
This code will require changes when MSYS2 upgrades from using OpenSSL 1.1.1 to 3.0.x.
Note that the `mswin` archive is only used with the 'mswin' head build, and it already uses OpenSSL 3.0.x.
> Windows - updates for using OpenSSL 3 in Ruby 3.2 & head

- dist/index.js
- windows.js
Also, ran `yarn upgrade`
Ideally, I need to push a PR to https://github.com/ruby/setup-msys2-gcc before this is added to a new release.
Also, this will fail, as it's looking for an archive file from the above that doesn't exist until I make the PR...
> Updates for Windows MSYS2 update to OpenSSL 3

- action.yml
- common.js
- dist/index.js
- index.js
- ruby-builder.js
Fixes https://github.com/ruby/setup-ruby/issues/242
> Consider a different $RUNNER_TOOL_CACHE than the default as a self-hosted runner and add self-hosted input

- common.js
- dist/index.js
- ruby-builder.js
- windows.js
> Use the default tool cache path on self-hosted runners matching a GH-hosted runner image

- dist/index.js
- windows.js
- yarn.lock
1. MSYS2 recently changed the folder that the ssl cert file is located in.  'Git for Windows' is built with MSYS2.  The most recent version has the files in `etc/ssl`, older versions have them in `ssl`.  Code now looks in both locations.  This file is needed for Windows Rubies 2.3 and earlier, as they don't include a cert file, and the code uses the cert file included with 'Git for Windows'...
2. The ruby-loco mswin build now has a bundled cert file.  Removed the code for that.
3. Updated `yarn.lock`.
Note that the Actions images that are currently rolling out will not work without this PR.  Sorry, I forgot about the 'Git for Windows' change due to the MSYS2 change...
> Update yarn.lock, remove Windows mswin ssl cert related code

- dist/index.js
- package.json
- yarn.lock
See #483.  I can't look at it until (hopefully) this weekend.
It may be a bug with @actions/cache, as I tried both 3.1.4 & 3.2.1.  Not.sure.
> Lock @actions/cache to 3.0.6, later versions break bundler caching

- bundler.js
- dist/index.js
- package.json
- yarn.lock
See also https://github.com/actions/toolkit/pull/1378.
If the above PR is accepted, the change to bundler.js isn't needed, but it's a good idea, as we don't want the value to change when passed to [@actions/cache's](https://github.com/actions/toolkit/tree/main/packages/cache) code...
Currently, we use:
```js
cache.restoreCache(paths, key, restoreKeys)
// then later the following may run
cache.saveCache(paths, key)
```
Current code in [@actions/cache](https://github.com/actions/toolkit/tree/main/packages/cache) modifies `paths` during the call to `cache.restoreCache`.  Since the verification hash is based on that array, `cache.saveCache` will associate a verification key with the saved cache that `cache.restoreCache` will never match...
> Fix cache with @actions/cache

- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
On the 4th of September 2023 `actions/checkout` released its version 4.
With this PR I bump all the occurrences of `actions/checkout@v3` in the CI to its newer version. Additionally, I have also updated the `README.md` to reflect the current changes (and I have removed a few trailing whitespaces too).
For more information about the new version of `actions/checkout` take a look at their release page: https://github.com/actions/checkout/releases/tag/v4.0.0
> Update actions/checkout to v4

- bundler.js
- dist/index.js
- Resolve https://github.com/ruby/setup-ruby/issues/531
> Consider BUNDLE_ONLY in cache key

- dist/index.js
- index.js
* See https://github.com/ruby/setup-ruby/issues/543
> Explicitly exit after this action runs to not wait for hanging promises

- .github/workflows/test.yml
- action.yml
- dist/index.js
- index.js
- rubygems.js
Fixes using 'rubygems; latest' for MRI Ruby 2.3 and later.  I tried updating Ruby 2.2 and got errors for two different versions.
`gem update --system` will not allow a bounded version, only an exact version.  So, code is somewhat brittle if new patch releases are done for older RubyGems versions.
Code works same as existing for non MRI Rubies.
One thing I wasn't sure about is whether Ruby master/head builds should not have anything done for 'rubygems; latest'.  Sometime this year I think the RubyGems version was a pre-release, so latest would install an earlier version?  Not.Sure.
Happy Holidays...
> Fixup 'rubygems: latest'

- .github/workflows/test.yml
- action.yml
- dist/index.js
- rubygems.js
> Fixup Rubygems latest to work with Rubies < 2.3

- .github/workflows/test.yml
- action.yml
- common.js
- dist/index.js
- index.js
- windows.js
Adds a `windows-toolchain` input.
1. Only affects Windows Rubies.
2. Current PR allows only one optional setting, which is `none`.  It installs the selected Ruby and adds it to `PATH`.  No build tools are installed/activated.  Hence, no extension gems can be compiled/installed via bundler.
Closes #562
> Add windows-toolchain input

- README.md
The current URL links to a generic "Using GitHub-hosted runners" page instead of "Supported runners and hardware resources" with a list of supported runners.
> Update url to supported

- .github/workflows/test.yml
- README.md
- common.js
- dist/index.js
Resolves #595
As I understand it, https://github.com/ruby/ruby-builder/pull/17 is needed as a preparation task
> Support ubuntu-24.04-x64

- .github/workflows/test.yml
Unfortunately, we lost `macos-arm-oss` runner from ruby org.
> Removed macos-arm-oss from GitHub Actions

- README.md
Clarify that the pre-installed Windows MSYS2 packages vary by Actions image (Windows 2019 vs Windows 2022)
Closes #641
> README.md - Windows - clarify installed packages, 2022 vs 2019

- README.md
Fixes https://github.com/ruby/setup-ruby/issues/650
Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>
> `README.md`: Mention link to supported Ruby versions for GitHub-hosted runners

- README.md
We could add links to examples and Ruby's documentation but I thought let's keep it short to start with.
> Add some details about using asan build.

- .github/workflows/test.yml
- dist/index.js
- rubygems.js
If set up `rubygems: latest` in workflow,
it will cause the error with Ruby 3.0 because the latest rubygems does not support Ruby 3.0.
Ref. https://rubygems.org/gems/rubygems-update
```
Updating RubyGems
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/gem --version
3.2.33
Default RubyGems version is 3.2.33
Updating RubyGems to latest version
/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/gem update --system
ERROR:  Error installing rubygems-update:
rubygems-update-3.6.1 requires Ruby version >= 3.1.0. The current ruby version is 3.0.7.220.
ERROR:  While executing gem ... (NoMethodError)
undefined method `version' for nil:NilClass
Updating rubygems-update
Took   2.86 seconds
Error: The process '/opt/hostedtoolcache/Ruby/3.0.7/x64/bin/gem' failed with exit code 1
```
```
uses: ruby/setup-ruby@v1
with: …
```
> Fixes the latest rubygems installation error with Ruby 3.0

- .github/workflows/test.yml
- dist/index.js
- package.json
- yarn.lock
The cache backend service has been rewritten from the ground up for improved performance and reliability. The [@actions/cache](https://github.com/actions/toolkit/tree/main/packages/cache) package now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of **February 1st, 2025**. The legacy service will also be sunset on the same date. Changes in this release are **fully backward compatible**.
If you do not upgrade, all workflow runs using any of the deprecated [@actions/cache](https://github.com/actions/toolkit/tree/main/packages/cache) packages will fail.
Upgrading to the recommended version should not break or require any changes to your workflows beyond the changes in this PR.
Please cut a new release after merging this PR.
More details: …
> Time sensitive: upgrade `@actions/cache` to `^4.0.0`

- dist/index.js
- package.json
- yarn.lock
With the update `"@actions/cache": "^4.0.0"`, along with the dependency on `"@actions/core": "^1.10.0"`, two versions of @actions/core are listed in `yarn.lock`.
Update `package.json` to use `"@actions/core": "^1.11.1"`.
JFYI, this started while I was working on adding `windows-2025`.  Also, haven't looked at it yet, but 1.11.1 adds a `platform` object, see:
https://github.com/actions/toolkit/tree/main/packages/core#platform-helper
We may be able to use `platform` in the code here...
> yarn.lock - Remove @actions/core 1.10.1, use @actions/core 1.11.1

- dist/index.js
- index.js
See #716  for explanation
Tested on one of my projects: https://github.com/jtannas/katachi/actions/runs/13660430691/job/38190080032?pr=19
While it might be cool for it to attempt each ruby version in order (aka. mimic ASDF parsing) or to treat multiple `.tool-versions` entries as a matrix, that's way beyond what I need and am comfortable tackling as a first PR.
> [Fixes #716] deal with multiple versions in .tool-versions

- dist/index.js
- index.js
close: #719
This PR fixes a regression introduced in PR #717, where the tool fails to correctly parse the Ruby version from .tool-versions when multiple spaces exist between the tool name and version.
> bugfix: Fix bug that version cannot be parsed in .tool-versions

- common.js
- dist/index.js
- index.js
- ruby-builder.js
JRuby 10 requires Java 21. Since the previous default was 17 and all JRuby releases should work fine on 21, we do this for all JRuby installs.
Implements #718
> Switch JAVA_HOME to 21 for JRuby

- common.js
- dist/index.js
- ruby-builder.js
Apparently this exec errors when the subprocess fails rather than returning an error code. This causes the whole setup process to terminate. This patch catches the error and uses that to indicate failure to launch.
Hopefully will address the issue in https://github.com/ruby/jruby-dev-builder/pull/10#issuecomment-2722058138
> Handle exec error

- dist/index.js
- windows.js
Fix for GCC 15 being preinstalled on win2019
> Handle win2019 gcc issue

- dist/index.js
- windows.js
See https://github.com/rubygems/rubygems/pull/8700#issuecomment-2887357470
@eregon Can you please take a look?
> Fix a regression where MAKE on windows has an extra space at the end

- bundler.js
- dist/index.js
- rubygems.js
Like every time I release a version of RubyGems dropping support for a EOL Ruby, I forgot to update `ruby/setup-ruby` before the release, so that `rubygems: latest` does not break 😅
Fixing it now.
This issue was fixed by https://github.com/rubygems/rubygems/pull/7334, shipped with RubyGems 3.5.4. That version of RubyGems comes by default with Ruby 3.3.1 or higher, so I believe we just need one more future update similar to this one right before shipping a RubyGems version dropping support for Ruby 3.2. I will try to remember that one last time!
> Add workaround for Ruby 3.1 after RubyGems 3.7.0 release

- .github/workflows/test.yml
- dist/index.js
- index.js
Reimplementation of #785, but with checking the case of a missing lockfile (caused by a missing Gemfile).
While the case of user `bundler-cache: true` with a missing Gemfile is strange, it is something that was working prior to #785.
Closes #783
@eregon Please review.
> Add printing of the lockfile after installation (retry)

- README.md
Use current ruby version in examples.
> Update ruby version in `README.md`

- .github/workflows/test.yml
- Reverts https://github.com/ruby/setup-ruby/commit/f2f42b7848feff522ffa488a5236ba0a73bccbdd now the issue is fixed upstream
- Reinstates testing against JRuby 9.4 (I believe when this was last reviewed 10.0 was unreleased so `jruby` was testing 9.4 and `jruby-head` was testing 10.0)
If you're not comfortable adding yet more jobs, can reconsider adding 9.4. Having said that, given the significant changes and major Java version increase, possibly wise to test both given they are both supported.
> Reinstate testing against jruby 9.4 and head

- bundler.js
- dist/index.js
- index.js
Currently, the lockfile gets printed after `bundle install` finished. This could be too late when `bundle install` fails for whatever reason.
I have a workflow that failed like this:
<details><summary>Logs</summary>
<p>
```
55s
Run ruby/setup-ruby@v1
Modifying PATH
Downloading Ruby
Extracting  Ruby
Print Ruby version
Installing Bundler
> bundle install
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle config --local path /home/runner/work/rubocop/rubocop/vendor/bundle
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle lock
Fetching source index from https://rubygems.org/
Network error while fetching
https://rubygems.org/quick/Marshal.4.8/asciidoctor-0.0.1.gemspec.rz (Connection
reset by peer - SSL_connect)
Error: The process '/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/bundle' failed with exit code …
```
> Print lockfile contents earlier
